spring.application.name=expense-service
spring.datasource.url=jdbc:postgresql://localhost:5433/expense_db
spring.datasource.username=shubhambagate
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
