CREATE TABLE expenses (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          user_id BIGINT,
                          user_email VARCHAR(255),
                          amount NUMERIC(38, 2),
                          currency VARCHAR(255),
                          merchant VARCHAR(255),
                          category VARCHAR(255),
                          description VARCHAR(255),
                          expense_date DATE,
                          source VARCHAR(255),
                          raw_message_id VARCHAR(255),
                          created_at TIMESTAMP,
                          updated_at TIMESTAMP
);